config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :ingredients
  resources :plates
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes
  has_many :plates, through: :recipes
  validates_presence_of :description
end

app/models/plate.rb
class Plate < ApplicationRecord
  has_many :recipes
  has_many :ingredients, -> { order(description: :asc) }, through: :recipes

  validates_presence_of :description
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :plate
  belongs_to :ingredient
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :address, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to :ingredients, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to :ingredients, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:description)
    end
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]

  # GET /plates
  # GET /plates.json
  def index
    @plates = Plate.all
  end

  # GET /plates/1
  # GET /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
  end

  # GET /plates/1/edit
  def edit
  end

  # POST /plates
  # POST /plates.json
  def create
    @plate = Plate.new(plate_params)

    respond_to do |format|
      if @plate.save
        format.html { redirect_to @plate, notice: 'Plate was successfully created.' }
        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plates/1
  # PATCH/PUT /plates/1.json
  def update
    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to @plate, notice: 'Plate was successfully updated.' }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plates/1
  # DELETE /plates/1.json
  def destroy
    @plate.destroy
    respond_to do |format|
      format.html { redirect_to plates_url, notice: 'Plate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:description, :price, :prepare_time, :ingredient_ids => [])
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurant = Restaurant.first
  end

  # GET /restaurants/1/edit
  def edit
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to :restaurants, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @restaurant = Restaurant.first
    @plates     = Plate.order(:description).all
    render layout: 'public'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :description %></strong>
    <%= form.text_field :description, id: :ingredient_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<%= link_to 'New Ingredient', new_ingredient_path %>

<br><br>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th class="actions">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.description %></td>
      <td class="actions">
        <%= link_to 'Edit', edit_ingredient_path(ingredient) %>
        <%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/layouts/_management_nav.html.erb
<nav>
  <%= link_to 'FomeZero', root_path, class: 'brand' %>
  <ul class="menu right">
    <li class="menu-item">
      <%= link_to 'Restaurant', restaurants_path, class: 'menu-item-link' %>
      <%= link_to 'Plates', plates_path, class: 'menu-item-link' %>
      <%= link_to 'Ingredients', ingredients_path, class: 'menu-item-link' %>
    </li>
  </ul>
</nav>

app/views/layouts/_public_nav.html.erb
<nav>
  <%= link_to 'FomeZero', root_path, class: 'brand' %>
  <ul class="menu right">
    <li class="menu-item">
      <%= link_to 'Management', restaurants_path, class: 'menu-item-link' %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fomezero</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render file: 'layouts/_management_nav.html.erb' %>
    <section>
      <%= yield %>
    </section>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fomezero</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render file: 'layouts/_public_nav.html.erb' %>
  <%= yield %>
</body>
</html>

app/views/plates/_form.html.erb
<%= form_with(model: plate, local: true) do |form| %>
  <% if plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
      <% plate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :description %></strong>
    <%= form.text_field :description, id: :plate_description %>
  </div>

  <div class="field">
    <strong><%= form.label :price %></strong>
    <%= form.text_field :price, id: :plate_price %>
  </div>

  <div class="field">
    <strong><%= form.label :prepare_time %></strong>
    <%= form.number_field :prepare_time, id: :plate_prepare_time %>
  </div>

  <div class="field">
    <strong>Ingredients</strong>
    <% Ingredient.all.each do |ingredient| %>
      <ul>
        <li>
          <%= check_box_tag "plate[ingredient_ids][]", ingredient.id, @plate.ingredients.include?(ingredient) %>
          <%= ingredient.description %>
        </li>
      </ul>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plates/edit.html.erb
<h1>Editing Plate</h1>

<%= render 'form', plate: @plate %>

<%= link_to 'Show', @plate %>

app/views/plates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plates</h1>

<%= link_to 'New Plate', new_plate_path %>

<br><br>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th>Prepare time</th>
      <th>Ingredients</th>
      <th class="actions">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @plates.each do |plate| %>
    <tr>
      <td><%= plate.description %></td>
      <td><%= plate.price %></td>
      <td><%= plate.prepare_time %> min</td>
      <td>
        <ul>
          <% plate.ingredients.each do | ingredient | %>
            <li><%= ingredient.description %></li>
          <% end %>
        </ul>
      </td>
      <td class="actions">
        <%= link_to 'Show', plate %>
        <%= link_to 'Edit', edit_plate_path(plate) %>
        <%= link_to 'Destroy', plate, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/plates/new.html.erb
<h1>New Plate</h1>

<%= render 'form', plate: @plate %>

app/views/plates/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @plate.description %></h1>

<p>
  <strong>Price:</strong>
  <%= @plate.price %>$
</p>

<p>
  <strong>Prepare time:</strong>
  <%= @plate.prepare_time %> minutes
</p>

<div>
  <strong>Ingredients:</strong>
  <ul>
    <% @plate.ingredients.each do | ingredient | %>
      <li><%= ingredient.description %></li>
    <% end %>
  </ul>
</div>

<%= link_to 'Edit', edit_plate_path(@plate) %>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :name %></strong>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <strong><%= form.label :address %></strong>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="field">
    <strong><%= form.label :phone %></strong>
    <%= form.text_field :phone, id: :restaurant_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurant Information</h1>

<br><br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th class="actions">Edit</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @restaurant.name %></td>
      <td><%= @restaurant.address %></td>
      <td><%= @restaurant.phone %></td>
      <td class="actions">
        <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/welcome/_plate_item.html.erb
<hr>

<div class="plates-item">
  <h3 class="strong">
    #<%= index + 1 %> <%= plate.description %>
  </h3>
  <p>
    <span class="strong">Prepare time:</span>
    <%= plate.prepare_time %> minutes
  </p>
  <p>
    <span class="strong">Price:</span>
    <%= plate.price %>$
  </p>

  <h4>Ingredients:</h4>
  <span>
    <% plate.ingredients.each do | ingredient | %>
    - <%= ingredient.description %>
    <% end %>
  </span>
</div>

app/views/welcome/_plates.html.erb
<section id="plates">
  <h2>Menu</h2>

  <% @plates.each_with_index do | plate, index | %>
    <%= render 'plate_item', plate: plate, index: index %>
  <% end %>
</section>

app/views/welcome/_restaurant.html.erb
<section id="restaurant">
  <h1><%= restaurant.name %></h1>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= restaurant.phone %>
  </p>
</section>

app/views/welcome/index.html.erb
<%= render 'restaurant', restaurant: @restaurant %>
<%= render 'plates', plates: @plates %>